databases:
  - name: gestao-moradias-db
    plan: free
    databaseName: gestao_moradias
    user: gm_user

services:
  
  - type: web
    name: gestao-moradias-backend
    plan: free
    runtime: docker
    repo: https://github.com/juniorgalindo1990/gestao-moradias
    branch: main
    autoDeploy: true
    healthCheckPath: /actuator/health
    dockerfilePath: ./backend/Dockerfile
    envVars:
      
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${gestao-moradias-db.host}:${gestao-moradias-db.port}/${gestao-moradias-db.database}?sslmode=require

      
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: gestao-moradias-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: gestao-moradias-db
          property: password

      
      - key: JWT_SECRET
        generateValue: true

      
      - key: FRONTEND_URL
        value: "https://gestao-moradias-frontend.onrender.com"

 
  - type: web
    name: gestao-moradias-frontend
    plan: free
    runtime: docker
    repo: https://github.com/juniorgalindo1990/gestao-moradias
    branch: main
    autoDeploy: true
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      
      - key: NG_APP_API_URL
        value: "https://gestao-moradias-backend.onrender.com"
